impl
Change-Id: I9cb90d63f38d6887a7afe41869807616e7b66a99

diff --git a/dotfiles/extrarc b/dotfiles/extrarc
--- a/dotfiles/extrarc
+++ b/dotfiles/extrarc
@@ -457,4 +457,42 @@ sp_ltc(){
 }
 
 alias sp_bitcoin_table="coinmon"
+
+
+goto_pid() {
+  if [ $# -lt 1 ]; then
+    echo "Missing pid argument" 1>&2
+    return 1
+  fi
+  local proc="/proc/${1}"
+  if [ ! -e "${proc}" ]; then
+    echo "Process for pid: '${1}' is not running" 1>&2
+    return 2
+  fi
+  local tmux_pane="$(cat ${proc}/environ | tr '\0' '\n' | grep '^TMUX_PANE=')"
+  if [ ! $? -eq 0 ]; then
+    echo "Process not opened in tmux" 1>&2
+    return 3
+  fi
+
+  if [[ ! "${tmux_pane}" =~ '^TMUX_PANE=(.+)' ]]; then
+    echo "???? ${tmux_pane}" 1>&2
+    return 4
+  fi
+  local pane="${match[1]}"
+
+  local tmp="$(tmux list-panes -a | grep ${pane})"
+  if [ ! $? -eq 0 ]; then
+    echo "pane: '${pane}' not found" 1>&2
+    return 5
+  fi
+
+  if [[ ! "${tmp}" =~ '^#:([0-9]+)\.([0-9]+)' ]]; then
+    echo "!!! ${tmp}" 1>&2
+    return 6
+  fi
+
+  tmux select-window -t "${match[1]}" && tmux select-pane -t "${match[2]}"
+}
+
 # vim: set ft=zsh:
