wip
Change-Id: I4bd1ca3e8db29f7009c58c6296d9431019bd2cd2

diff --git a/dotfiles/workrc b/dotfiles/workrc
--- a/dotfiles/workrc
+++ b/dotfiles/workrc
@@ -148,6 +148,9 @@ setup_ssh_eager() {
 
 
 ssh_192_168_0_90() {
+# Note: PS1 runs only once
+# echo 'export PS1="\n\u\e[0;34m:\e[0m\$(cat /tmp/product)\e[0;34m:\e[0m\w         [\$?][\$(date +%_H:%_M:%S)][\h]\n\$ "' > \${tmp_conf}
+# export PS1="\n\u\e[0;34m:\e[0m$(cat /tmp/product)\e[0;34m:\e[0m\w         [$?][$(date +%_H:%_M:%S)][\h]\n\$ "
   sshx() {
     local l_user="root"
     local l_pass="pass"
@@ -156,65 +159,68 @@ ssh_192_168_0_90() {
     local l_env_setup='ENV=$HOME/.shinit; export ENV;'
     local l_env=$(cat <<-END
 parhandclient set root.System.CaptureFrequencySet yes && parhandclient set root.System.CaptureModeSet yes &
-tmp_conf=\$(mktemp)
+tmp_conf2=$(mktemp)
+parhandclient get root.Brand.ProdNbr \${tmp_conf2} raw && mv \${tmp_conf2} /tmp/product &
+tmp_conf=$(mktemp)
 echo "alias ll=\"ls -alh\"" > \${tmp_conf}
-echo "alias systemctl_status=\"systemctl status audiocontrol monolith parhand ioboxd -l\"" >> \${tmp_conf} &&
-echo "alias systemctl_root=\"cd /usr/lib/systemd/system\"" >> \${tmp_conf} &&
-echo "alias port_scan=\"netstat -lnptux\"" >> \${tmp_conf} &&
-echo "alias sp-sd=\"cd /var/spool/storage/SD_DISK\"" >> \${tmp_conf} &&
+echo 'export PS1="\n\u\e[0;34m:\e[0m\$(cat /tmp/product)\e[0;34m:\e[0m\w         [\h]\n\$ "' >> \${tmp_conf}
+echo "alias systemctl_status=\"systemctl status audiocontrol monolith parhand ioboxd -l\"" >> \${tmp_conf}
+echo "alias systemctl_root=\"cd /usr/lib/systemd/system\"" >> \${tmp_conf}
+echo "alias port_scan=\"netstat -lnptux\"" >> \${tmp_conf}
+echo "alias sp-sd=\"cd /var/spool/storage/SD_DISK\"" >> \${tmp_conf}
 # AF_UNIX socket
-echo "alias unix_con=\"netstat -apnx\"" >> \${tmp_conf} &&
+echo "alias unix_con=\"netstat -apnx\"" >> \${tmp_conf}
 
-echo 'watch() {' >> \${tmp_conf} &&
-echo '  if [ -e /usr/bin/watch ]; then' >> \${tmp_conf} &&
-echo '    /usr/bin/watch \$@' >> \${tmp_conf} &&
-echo '  else' >> \${tmp_conf} &&
-echo '  while [ 1 ]; do' >> \${tmp_conf} &&
-echo '    echo \"-------------------------------------------------------------------------------\"' >> \${tmp_conf} &&
-echo '    eval \$1;' >> \${tmp_conf} &&
-echo '    sleep 1;' >> \${tmp_conf} &&
-echo '  done' >> \${tmp_conf} &&
-echo '  fi' >> \${tmp_conf} &&
-echo '}' >> \${tmp_conf} &&
+echo 'watch() {' >> \${tmp_conf}
+echo '  if [ -e /usr/bin/watch ]; then' >> \${tmp_conf}
+echo '    /usr/bin/watch \$@' >> \${tmp_conf}
+echo '  else' >> \${tmp_conf}
+echo '  while [ 1 ]; do' >> \${tmp_conf}
+echo '    echo \"-------------------------------------------------------------------------------\"' >> \${tmp_conf}
+echo '    eval \$1;' >> \${tmp_conf}
+echo '    sleep 1;' >> \${tmp_conf}
+echo '  done' >> \${tmp_conf}
+echo '  fi' >> \${tmp_conf}
+echo '}' >> \${tmp_conf}
 
-echo 'tree() {' >> \${tmp_conf} &&
-echo '  if [ -e /usr/bin/tree ]; then' >> \${tmp_conf} &&
-echo '    /usr/bin/tree \$@' >> \${tmp_conf} &&
-echo '  else' >> \${tmp_conf} &&
-echo '    ls -alhR1' >> \${tmp_conf} &&
-echo '  fi' >> \${tmp_conf} &&
-echo '}' >> \${tmp_conf} &&
+echo 'tree() {' >> \${tmp_conf}
+echo '  if [ -e /usr/bin/tree ]; then' >> \${tmp_conf}
+echo '    /usr/bin/tree \$@' >> \${tmp_conf}
+echo '  else' >> \${tmp_conf}
+echo '    ls -alhR1' >> \${tmp_conf}
+echo '  fi' >> \${tmp_conf}
+echo '}' >> \${tmp_conf}
 
-echo 'vim() {' >> \${tmp_conf} &&
-echo '  if [ -e  /usr/bin/vim ]; then' >> \${tmp_conf} &&
-echo '    /usr/bin/vim \$@' >> \${tmp_conf} &&
-echo '  elif [ -e  /usr/bin/vim.tiny ]; then' >> \${tmp_conf} &&
-echo '    /usr/bin/vim.tiny \$@' >> \${tmp_conf} &&
-echo '  else' >> \${tmp_conf} &&
-echo '    vi \$@' >> \${tmp_conf} &&
-echo '  fi' >> \${tmp_conf} &&
-echo '}' >> \${tmp_conf} &&
+echo 'vim() {' >> \${tmp_conf}
+echo '  if [ -e  /usr/bin/vim ]; then' >> \${tmp_conf}
+echo '    /usr/bin/vim \$@' >> \${tmp_conf}
+echo '  elif [ -e  /usr/bin/vim.tiny ]; then' >> \${tmp_conf}
+echo '    /usr/bin/vim.tiny \$@' >> \${tmp_conf}
+echo '  else' >> \${tmp_conf}
+echo '    vi \$@' >> \${tmp_conf}
+echo '  fi' >> \${tmp_conf}
+echo '}' >> \${tmp_conf}
 
-echo 'gdb() {' >> \${tmp_conf} &&
-echo '  echo "set auto-load safe-path /" > ~/.gdbinit' >> \${tmp_conf} &&
-echo '  /usr/bin/gdb \$@' >> \${tmp_conf} &&
-echo '}' >> \${tmp_conf} &&
+echo 'gdb() {' >> \${tmp_conf}
+echo '  echo "set auto-load safe-path /" > ~/.gdbinit' >> \${tmp_conf}
+echo '  /usr/bin/gdb \$@' >> \${tmp_conf}
+echo '}' >> \${tmp_conf}
 
-echo "alias dmesg_tail=\"while true; do dmesg -c ; sleep 1 ; done\"" >> \${tmp_conf} &&
+echo "alias dmesg_tail=\"while true; do dmesg -c ; sleep 1 ; done\"" >> \${tmp_conf}
 
-echo "alias systemd_failed=\"systemctl --state=failed\"" >> \${tmp_conf} &&
+echo "alias systemd_failed=\"systemctl --state=failed\"" >> \${tmp_conf}
 
-echo "info() {" >> \${tmp_conf} &&
-echo '  echo "product: \$(parhandclient get root.Brand.ProdShortName)"' >> \${tmp_conf} &&
-echo '  echo "HWID: \$(bootblocktool -x HWID)"' >> \${tmp_conf} &&
+echo "info() {" >> \${tmp_conf}
+echo '  echo "product: \$(parhandclient get root.Brand.ProdShortName)"' >> \${tmp_conf}
+echo '  echo "HWID: \$(bootblocktool -x HWID)"' >> \${tmp_conf}
 # TODO show ip "ip addr show dev eth0 scope global | grep inet"
-echo "  bootblocktool -lw" >> \${tmp_conf} &&
-echo "  ip -4 addr show eth0 scope global | tail -2 | head -1 | xargs" >> \${tmp_conf} &&
-echo "  echo " >> \${tmp_conf} &&
-echo "}" >> \${tmp_conf} &&
+echo "  bootblocktool -lw" >> \${tmp_conf}
+echo "  ip -4 addr show eth0 scope global | tail -2 | head -1 | xargs" >> \${tmp_conf}
+echo "  echo " >> \${tmp_conf}
+echo "}" >> \${tmp_conf}
 
-echo "f() {" >> \${tmp_conf} &&
-echo '  find -iname "*\${1}*"' >> \${tmp_conf} &&
+echo "f() {" >> \${tmp_conf}
+echo '  find -iname "*\${1}*"' >> \${tmp_conf}
 echo "}" >> \${tmp_conf}
 mv \${tmp_conf} ~/.shinit
 END
@@ -843,7 +849,35 @@ deploy_single_192_168_0_90(){
   return $res
 }
 
-function rtags_all(){
+# TODO sshfs mount camera in some work dir that will be used by makefile
+# TODO find command to setup env(to override dest) and run make with corretch binaries
+#TODO maybe touch all sources in $project_dir?
+deploy_192_168_0_90(){
+  if ! valid_build_dir; then
+    return 1
+  fi
+
+  axis_enable_root_192_168_0_90
+  $HOME/development/axis/tpp/ff enable-ssh
+
+  local FAILED=()
+  for CURRENT in "${@}"; do
+    deploy_single_192_168_0_90 "${CURRENT}"
+    if [ ! $? -eq 0 ]; then
+      FAILED+=("${CURRENT}")
+    fi
+  done
+
+  if [ ${#FAILED[@]} -gt 0 ]; then
+    # notify-send "deploy '${project}' [FAILED]"
+    echo "\n\nFAILED:"
+    for CURRENT in "${FAILED[@]}"; do
+    echo "- ${CURRENT}"
+    done
+  fi
+}
+
+rtags_all(){
   if ! valid_build_dir; then
     return 1
   fi
